[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmd = "./mvnw clean package -DskipTests"

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar"

[variables]
JAVA_VERSION = "17"
